### ISSUE TITLE
No module named 'flearn.models.nist.stacked_lstm'

### ISSUE THREAD

**Issue by Mlair77** [litian96/FedProx#1]
hey~
when run main.py 
have an error:
Traceback (most recent call last):

  File "<ipython-input-10-928a22c23719>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/federated learning/code/FedProx-master/main.py', wdir='C:/Users/Administrator/Desktop/federated learning/code/FedProx-master')

  File "E:\anaconda\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/federated learning/code/FedProx-master/main.py", line 130, in <module>
    main()

  File "C:/Users/Administrator/Desktop/federated learning/code/FedProx-master/main.py", line 118, in main
    options, learner, optimizer = read_options()

  File "C:/Users/Administrator/Desktop/federated learning/code/FedProx-master/main.py", line 94, in read_options
    mod = importlib.import_module(model_path)

  File "E:\anaconda\Anaconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 978, in _gcd_import

  File "<frozen importlib._bootstrap>", line 961, in _find_and_load

  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 978, in _gcd_import

  File "<frozen importlib._bootstrap>", line 961, in _find_and_load

  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'flearn.models.nist.stacked_lstm'

And flearn.models.nist.stacked_lstm does not exist exactly. Why?
Thank you so much.

**Comment by litian96** [comment]
We explore different datasets using different models (both convex and non-convex). Each dataset is associated with a unique model. For example, the model for NIST is `mclr`, defined in `flearn/models/nist/mclr.py`. `stacked_lstm` is the model for Shakespeare.
See https://github.com/litian96/FedProx/blob/master/README.md#run-on-real-federated-datasets for more details.

Hope that helps!

**Comment by Mlair77** [comment]
thank you so much~~

**Comment by fanfan-97** [comment]
I have the same problem, how can I solve it?

**Comment by yangtieliu** [comment]
even if i migrate stacked_lstm.py to nist folder ,i still have this error,how can i fix it?
or i change the default value of model from stacked_lstm to mclr,i still have a similar error.
