### ISSUE TITLE
ModuleNotFoundError: No module named 'FedML'

### ISSUE THREAD

**Issue by mustain-billah** [litian96/FedProx#23]
After running this: !python experiments/centralized/moleculenet/molecule_classification_multilabel.py

Getting this Error Message:  
Traceback (most recent call last):
  File "experiments/centralized/moleculenet/molecule_classification_multilabel.py", line 11, in <module>
    from data_preprocessing.molecule.data_loader import get_dataloader, get_data
  File "/content/drive/My Drive/Colab Notebooks/FedGraphNN/data_preprocessing/molecule/data_loader.py", line 12, in <module>
    from FedML.fedml_core.non_iid_partition.noniid_partition import partition_class_samples_with_dirichlet_distribution
ModuleNotFoundError: No module named 'FedML'

**Comment by litian96** [comment]
From the error msg, I assume you are referring to some other repo (rather than FedProx)?
